### ISSUE TITLE
Live 11 to 10

### ISSUE THREAD

**Issue by oomek** [trobonox/abletonconvert#5]
Any chance to upgrade the script so it can handle conversions from Live 11.3.11 to Live 10?

**Comment by trobonox** [comment]
This is not a trivial task and currently not planned because it involves a lot more steps and would be difficult to reproduce across all files. 

You can try out Jukeblocks, I think the site offers this downgrade: https://jukeblocks.io/convert/

**Comment by oomek** [comment]
Thank you for your quick response. I've already tried jukeblocks, but unfortunately converted files are not opening.

**Comment by oomek** [comment]
![image](https://github.com/trobonox/abletonconvert/assets/2974860/fb74cc0b-2edb-4f65-b311-999b13056196)

Does it ring a bell?

**Comment by trobonox** [comment]
> ![image](https://github.com/trobonox/abletonconvert/assets/2974860/fb74cc0b-2edb-4f65-b311-999b13056196)
> 
> 
> 
> Does it ring a bell?

Not really. I haven't worked with the .als format for Live 11 since I only own a license for Live 10 so I'm afraid I can't help. Maybe you can try reaching out to the people at Jukeblocks.
